name: measure
description: Library for working with measurements, quantities and units.
version: 0.1.1+1
homepage: https://github.com/appsup-dart/measure
funding:
 - https://github.com/sponsors/rbellens

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  quiver: ^3.0.1
  intl: '>=0.17.0 <0.19.0'
  petitparser: ^5.1.0
  collection: ^1.14.0

dev_dependencies:
  test: ">=0.12.0 <2.0.0"
  pedantic: ^1.9.0
