name: measure
description: Library for working with measurements, quantities and units.
version: 0.0.1
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/firebase_dart

environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  quiver: '>=0.24.0 <1.0.0'
dev_dependencies: 
  unittest: '>=0.12.3 <0.13.0'