name: measure
description: Library for working with measurements, quantities and units.
version: 0.1.0-dev.2
homepage: https://github.com/appsup-dart/measure

environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  quiver: '>=0.24.0 <3.0.0'
  intl: '>=0.15.0 <0.17.0'
  petitparser: ^3.0.0
  collection: ^1.14.0

dev_dependencies:
  test: ">=0.12.0 <2.0.0"
  pedantic: ^1.9.0
