name: measure
description: Library for working with measurements, quantities and units.
version: 0.1.0-dev.3
homepage: https://github.com/appsup-dart/measure

environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  quiver: ^3.0.1
  intl: ^0.17.0
  petitparser: ^4.2.0
  collection: ^1.14.0

dev_dependencies:
  test: ">=0.12.0 <2.0.0"
  pedantic: ^1.9.0
