name: measure
description: Library for working with measurements, quantities and units.
version: 0.1.2+3
homepage: https://github.com/appsup-dart/measure
repository: https://github.com/appsup-dart/measure
funding:
 - https://github.com/sponsors/rbellens

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  quiver: ^3.0.1
  intl: '>=0.17.0 <0.21.0'
  petitparser: '>=5.1.0 <8.0.0'
  collection: ^1.14.0

dev_dependencies:
  test: ">=0.12.0 <2.0.0"
  lints: ^6.0.0
  melos: ^7.0.0

melos:
  useRootAsPackage: true

  ide:
    intellij: false

  command:
    version:
      linkToCommits: true
      workspaceChangelog: false

  scripts:
    preversion: 
      exec: dart test -j 1