name: measure
description: Library for working with measurements, quantities and units.
version: 0.1.2+1
homepage: https://github.com/appsup-dart/measure
funding:
 - https://github.com/sponsors/rbellens

environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  quiver: ^3.0.1
  intl: '>=0.17.0 <0.20.0'
  petitparser: '>=5.1.0 <7.0.0'
  collection: ^1.14.0

dev_dependencies:
  test: ">=0.12.0 <2.0.0"
  lints: '>=2.0.0 <5.0.0'
